language: objective-c
xcode_scheme: Universal
cache: bundler
matrix:
  include:
    - osx_image: xcode10.2
      rvm: 2.4.5
    - osx_image: xcode10.1
      rvm: 2.4.5
    - osx_image: xcode9.4
      rvm: 2.4.3
env:
  - XCODE_DESNITATION='platform=macOS'
script:
  - set -o pipefail && xcodebuild test -scheme "$TRAVIS_XCODE_SCHEME" -destination "$XCODE_DESNITATION" | bundle exec xcpretty -f `bundle exec xcpretty-travis-formatter`
before_install:
  - gem install bundler # to use bundler v2 which is not installed on travis image
