language: objective-c
xcode_scheme: Universal
cache: bundler
osx_image:
  - xcode10.2
  - xcode10.1
  - xcode9.4
env:
  - XCODE_DESNITATION='platform=macOS'
  - XCODE_DESNITATION='platform=tvOS Simulator,name=Apple TV'
  - XCODE_DESNITATION='platform=iOS Simulator,name=iPhone SE'
  - XCODE_DESNITATION='platform=iOS Simulator,name=iPhone SE,OS=10.3.1'
  - XCODE_DESNITATION='platform=iOS Simulator,name=iPhone 6s,OS=9.3'
script:
  - set -o pipefail && xcodebuild test -scheme "$TRAVIS_XCODE_SCHEME" -destination "$XCODE_DESNITATION" | bundle exec xcpretty -f `bundle exec xcpretty-travis-formatter`
before_install:
  - gem install bundler # to use bundler v2 which is not installed on travis image
rvm:
  - 2.4.5
  - 2.4.3
matrix:
  exclude:
    - osx_image: xcode10.2
      rvm: 2.4.3
    - osx_image: xcode10.1
      rvm: 2.4.3
    - osx_image: xcode9.4
      rvm: 2.4.5
